services:
  postgres:
    image: postgres:15
    container_name: nest-postgres
    environment:
      POSTGRES_USER: megha
      POSTGRES_PASSWORD: megha@123
      POSTGRES_DB: nestdb
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    container_name: nest-api
    command: npm run start:dev
    ports:
      - "3000:3000"
    env_file:
      - apps/backend/.env
    depends_on:
      - postgres
    volumes:
      - ./apps/backend:/app
      - /app/node_modules

volumes:
 pgdata:
